apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fastapi-demo

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - service-monitor.yaml

commonLabels:
  app: fastapi-demo
  managed-by: argocd
