apiVersion: v1
kind: Service
metadata:
  name: fastapi-demo
  namespace: fastapi-demo
  labels:
    app: fastapi-demo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
      nodePort: 30080
  selector:
    app: fastapi-demo
